import type { Metadata } from "next"
import PcSidebar from "@/components/PcSidebar"
import MobileNavbar from "@/components/MobileNavbar"
import Providers from "../Providers"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <div className="flex min-h-screen">
            <Providers>
                <PcSidebar />

                <main className="flex-1 pb-16 md:pb-0">
                    {children}
                </main>

                <MobileNavbar />
            </Providers>
        </div>
    )
}