import type { Metadata } from "next"
import PcSidebar from "@/components/PcSidebar"
import MobileNavbar from "@/components/MobileNavbar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <div className="flex min-h-screen">

            <PcSidebar />

            <main className="flex-1 pb-16 md:pb-0">
                {children}
            </main>

            <MobileNavbar />

        </div>
    )
}